iPlug2: APIBitmap Class Reference
APIBitmap Class Reference
IGraphics::Structs
A bitmap abstraction around the different drawing back end bitmap representations.
#include <IGraphicsStructs.h>
Public Member Functions
APIBitmap (BitmapData pBitmap, int w, int h, int scale, float drawScale)
APIBitmap constructor.
void SetBitmap (BitmapData pBitmap, int w, int h, int scale, float drawScale)
Used to initialise the members after construction.
BitmapData GetBitmap () const
int GetWidth () const
/todo
int GetHeight () const
/todo
int GetScale () const
/todo
float GetDrawScale () const
/todo
Detailed Description
A bitmap abstraction around the different drawing back end bitmap representations.
In most cases it does own the bitmap data, the exception being with NanoVG, where the image is loaded onto the GPU as a texture, but still needs to be freed. Most of the time end-users will deal with IBitmap rather than APIBitmap, which is used behind the scenes.
Definition at line 111 of file IGraphicsStructs.h.
Constructor & Destructor Documentation
APIBitmap::APIBitmap (BitmapData pBitmap, int w, int h, int scale, float drawScale) inline
APIBitmap constructor.
Parameters
pBitmap pointer or integer index (NanoVG) to the image data
w The width of the bitmap
h The height of the bitmap
scale An integer representing the scale of this bitmap in relation to a 1:1 pixel screen, e.g. 2 for an @2x bitmap
drawScale The draw scale at which this API bitmap was created (used in the context of layers)
Definition at line 121 of file IGraphicsStructs.h.
Member Function Documentation
BitmapData APIBitmap::GetBitmap () const inline
Returns
BitmapData /todo
Definition at line 155 of file IGraphicsStructs.h.
Referenced by IGraphicsCanvas::ApplyShadowMask(), IGraphicsCairo::ApplyShadowMask(), IGraphicsLice::ApplyShadowMask(), IGraphicsAGG::ApplyShadowMask(), IGraphicsCanvas::DrawBitmap(), IGraphicsCairo::DrawBitmap(), IGraphicsLice::DrawBitmap(), IGraphicsNanoVG::DrawBitmap(), IGraphicsAGG::DrawBitmap(), IGraphicsLice::DrawFittedBitmap(), IGraphicsLice::DrawRotatedBitmap(), IGraphicsCanvas::GetLayerBitmapData(), IGraphicsCairo::GetLayerBitmapData(), IGraphicsLice::GetLayerBitmapData(), IGraphicsNanoVG::GetLayerBitmapData(), and IGraphicsAGG::GetLayerBitmapData().
void APIBitmap::SetBitmap (BitmapData pBitmap, int w, int h, int scale, float drawScale) inline
Used to initialise the members after construction.
Parameters
pBitmap pointer or integer index (NanoVG) to the image data
w The width of the bitmap
h The height of the bitmap
scale An integer representing the scale of this bitmap in relation to a 1:1 pixel screen, e.g. 2 for an @2x bitmap
drawScale The draw scale at which this API bitmap was created (used in the context of layers)
Definition at line 145 of file IGraphicsStructs.h.
The documentation for this class was generated from the following file:
IGraphicsStructs.h