iPlug2: IPlugQueue< T > Class Template Reference
IPlugQueue< T > Class Template Reference final
A lock-free SPSC queue used to transfer data between threads based on MLQueue.h by Randy Jones based on https://kjellkod.wordpress.com/2012/11/28/c-debt-paid-in-full-wait-free-lock-free-queue/.
#include <IPlugQueue.h>
Public Member Functions
IPlugQueue (int size)
IPlugQueue constructor.
void Resize (int size)
/todo
bool Push (const T &item)
/todo
bool Pop (T &item)
/todo
size_t ElementsAvailable () const
/todo
const T & Peek ()
/todo useful for reading elements while a criterion is met.
bool WasEmpty () const
/todo
bool WasFull () const
/todo
Detailed Description
template<typename T>
class IPlugQueue< T >
A lock-free SPSC queue used to transfer data between threads based on MLQueue.h by Randy Jones based on https://kjellkod.wordpress.com/2012/11/28/c-debt-paid-in-full-wait-free-lock-free-queue/.
Definition at line 25 of file IPlugQueue.h.
Constructor & Destructor Documentation
template<typename T> IPlugQueue< T >::IPlugQueue (int size) inline
IPlugQueue constructor.
Parameters
size /todo
Definition at line 30 of file IPlugQueue.h.
Member Function Documentation
template<typename T> size_t IPlugQueue< T >::ElementsAvailable () const inline
/todo
Returns
size_t /todo
Definition at line 79 of file IPlugQueue.h.
template<typename T> const T& IPlugQueue< T >::Peek () inline
/todo useful for reading elements while a criterion is met.
Can be used like while IPlugQueue.ElementsAvailable() && q.peek().mTime < 100 { elem = q.pop() ... }
Returns
const T& /todo
Definition at line 88 of file IPlugQueue.h.
template<typename T> bool IPlugQueue< T >::Pop (T & item) inline
/todo
Parameters
item /todo
Returns
true /todo
false /todo
Definition at line 65 of file IPlugQueue.h.
template<typename T> bool IPlugQueue< T >::Push (const T & item) inline
/todo
Parameters
item /todo
Returns
true /todo
false /todo
Definition at line 48 of file IPlugQueue.h.
Referenced by IPlugAPIBase::DeferMidiMsg(), IPlugAPIBase::DeferSysexMsg(), and IPlugAPIBase::SendParameterValueFromAPI().
template<typename T> void IPlugQueue< T >::Resize (int size) inline
/todo
Parameters
size /todo
Definition at line 39 of file IPlugQueue.h.
Referenced by IPlugQueue< IVScopeControl::Data >::IPlugQueue().
template<typename T> bool IPlugQueue< T >::WasEmpty () const inline
/todo
Returns
true /todo
false /todo
Definition at line 97 of file IPlugQueue.h.
template<typename T> bool IPlugQueue< T >::WasFull () const inline
/todo
Returns
true /todo
false /todo
Definition at line 105 of file IPlugQueue.h.
The documentation for this class was generated from the following file:
IPlugQueue.h