iPlug2: IByteGetter Struct Reference
IByteGetter Struct Reference
IPlug::Structs
A helper class for IBtyeChunk and IBtyeStream that avoids code duplication.
#include <IPlugStructs.h>
Static Public Member Functions
static int GetBytes (const uint8_t *pData, int dataSize, void *pBuf, int size, int startPos)
/todo
static int GetStr (const uint8_t *pData, int dataSize, WDL_String &str, int startPos)
/todo
Detailed Description
A helper class for IBtyeChunk and IBtyeStream that avoids code duplication.
Definition at line 62 of file IPlugStructs.h.
Member Function Documentation
static int IByteGetter::GetBytes (const uint8_t * pData, int dataSize, void * pBuf, int size, int startPos) inline static
/todo
Parameters
pData /todo
dataSize /todo
pBuf /todo
size /todo
startPos /todo
Returns
int /todo
Definition at line 71 of file IPlugStructs.h.
Referenced by IByteChunk::GetBytes(), IByteStream::GetBytes(), and GetStr().
static int IByteGetter::GetStr (const uint8_t * pData, int dataSize, WDL_String & str, int startPos) inline static
/todo
Parameters
pData /todo
dataSize /todo
str /todo
startPos /todo
Returns
int /todo
Definition at line 88 of file IPlugStructs.h.
References GetBytes().
Referenced by IByteChunk::GetStr(), and IByteStream::GetStr().
The documentation for this struct was generated from the following file:
IPlugStructs.h