iPlug2: IOConfig Struct Reference
IOConfig Struct Reference
IPlug::Structs
An IOConfig is used to store bus info for each input/output configuration defined in the channel io string.
#include <IPlugStructs.h>
Public Member Functions
void AddBusInfo (ERoute direction, int NChans, const char *label="")
/todo
IBusInfo * GetBusInfo (ERoute direction, int index)
/todo
int NChansOnBusSAFE (ERoute direction, int index)
/todo
int NBuses (ERoute direction)
/todo
int GetTotalNChannels (ERoute direction) const
Get the total number of channels across all direction buses for this IOConfig.
bool ContainsWildcard (ERoute direction)
/todo
Public Attributes
WDL_PtrList< IBusInfo > mBusInfo [2]
Detailed Description
An IOConfig is used to store bus info for each input/output configuration defined in the channel io string.
Definition at line 421 of file IPlugStructs.h.
Member Function Documentation
void IOConfig::AddBusInfo (ERoute direction, int NChans, const char * label = "") inline
/todo
Parameters
direction /todo
NChans /todo
label /todo
Definition at line 435 of file IPlugStructs.h.
bool IOConfig::ContainsWildcard (ERoute direction) inline
/todo
Parameters
direction /todo
Returns
true /todo
false /todo
Definition at line 489 of file IPlugStructs.h.
IBusInfo* IOConfig::GetBusInfo (ERoute direction, int index) inline
/todo
Parameters
direction /todo
index /todo
Returns
IBusInfo* /todo
Definition at line 444 of file IPlugStructs.h.
int IOConfig::GetTotalNChannels (ERoute direction) const inline
Get the total number of channels across all direction buses for this IOConfig.
Parameters
direction /todo
Returns
int /todo
Definition at line 475 of file IPlugStructs.h.
Referenced by IPlugProcessor< T >::LegalIO().
int IOConfig::NBuses (ERoute direction) inline
/todo
Parameters
direction /todo
Returns
int /todo
Definition at line 467 of file IPlugStructs.h.
int IOConfig::NChansOnBusSAFE (ERoute direction, int index) inline
/todo
Parameters
direction /todo
index /todo
Returns
int /todo
Definition at line 454 of file IPlugStructs.h.
Referenced by IPlugProcessor< T >::MaxNChannelsForBus(), and IPlugProcessor< T >::ParseChannelIOStr().
The documentation for this struct was generated from the following file:
IPlugStructs.h