iPlug2: IPattern Struct Reference
IPattern Struct Reference
IGraphics::Structs
Used to store pattern information for gradients.
#include <IGraphicsStructs.h>
Public Member Functions
IPattern (EPatternType type)
/todo
IPattern (const IColor &color)
/todo
int NStops () const
/todo
const IColorStop & GetStop (int idx) const
/todo
void AddStop (IColor color, float offset)
/todo
void SetTransform (float xx, float yx, float xy, float yy, float x0, float y0)
/todo
void SetTransform (const IMatrix &transform)
/todo
Static Public Member Functions
static IPattern CreateLinearGradient (float x1, float y1, float x2, float y2, const std::initializer_list< IColorStop > &stops={})
/todo
static IPattern CreateLinearGradient (const IRECT &bounds, EDirection direction, const std::initializer_list< IColorStop > &stops={})
/todo
static IPattern CreateRadialGradient (float x1, float y1, float r, const std::initializer_list< IColorStop > &stops={})
/todo
Public Attributes
EPatternType mType
EPatternExtend mExtend
IColorStop mStops [16]
int mNStops
IMatrix mTransform
Detailed Description
Used to store pattern information for gradients.
Definition at line 2111 of file IGraphicsStructs.h.
Constructor & Destructor Documentation
IPattern::IPattern (EPatternType type) inline
/todo
Parameters
type /todo
Definition at line 2121 of file IGraphicsStructs.h.
IPattern::IPattern (const IColor & color) inline
/todo
Parameters
color /todo
Definition at line 2127 of file IGraphicsStructs.h.
Member Function Documentation
void IPattern::AddStop (IColor color, float offset) inline
/todo
Parameters
color /todo
offset /todo
Definition at line 2231 of file IGraphicsStructs.h.
References GetStop().
Referenced by TestShadowGradientControl::Draw(), and TestColorControl::OnResize().
static IPattern IPattern::CreateLinearGradient (float x1, float y1, float x2, float y2, const std::initializer_list< IColorStop > & stops = {}) inline static
/todo
Parameters
x1 /todo
y1 /todo
x2 /todo
y2 /todo
stops /todo
Returns
IPattern /todo
Definition at line 2140 of file IGraphicsStructs.h.
Referenced by TestShadowGradientControl::Draw(), and TestColorControl::OnResize().
static IPattern IPattern::CreateLinearGradient (const IRECT & bounds, EDirection direction, const std::initializer_list< IColorStop > & stops = {}) inline static
/todo
Parameters
bounds /todo
direction /todo
stops /todo
Returns
IPattern /todo
Definition at line 2173 of file IGraphicsStructs.h.
static IPattern IPattern::CreateRadialGradient (float x1, float y1, float r, const std::initializer_list< IColorStop > & stops = {}) inline static
/todo
Parameters
x1 /todo
y1 /todo
r /todo
stops /todo
Returns
IPattern /todo
Definition at line 2199 of file IGraphicsStructs.h.
const IColorStop& IPattern::GetStop (int idx) const inline
/todo
Parameters
idx /todo
Returns
const IColorStop& /todo
Definition at line 2223 of file IGraphicsStructs.h.
Referenced by AddStop(), IGraphicsLice::ApplyShadowMask(), IPanelControl::Draw(), IGraphicsNanoVG::PathFill(), and IGraphicsNanoVG::PathStroke().
int IPattern::NStops () const inline
/todo
Returns
int /todo
Definition at line 2215 of file IGraphicsStructs.h.
void IPattern::SetTransform (float xx, float yx, float xy, float yy, float x0, float y0) inline
/todo
Parameters
xx /todo
yx /todo
xy /todo
yy /todo
x0 /todo
y0 /todo
Definition at line 2246 of file IGraphicsStructs.h.
void IPattern::SetTransform (const IMatrix & transform) inline
/todo
Parameters
transform /todo
Definition at line 2253 of file IGraphicsStructs.h.
The documentation for this struct was generated from the following file:
IGraphicsStructs.h